### PR TITLE
Again

### PR DESCRIPTION
**Pull request by sonyeric**
OK?

### CODE REVIEW

**Comment by sonyeric** [comment]
LGTM

**Review by mxylin — CHANGES_REQUESTED** [review]
it seems to me that there are duplicated lines

àbćdęfghïjkłmñœpqrštūvwxÿž
àbćdęfghïjkłmñœpqrštūvwxÿž

**Review by mxylin — APPROVED** [review]
looks good to me now, thanks for the fix

**Comment by sonyeric** [comment]
Great!

**Pull request merged**
